apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-to-api-gateway
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: "{{ .Release.Name }}-app"
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: ingress
      toPorts:
        - ports:
            - port: {{ .Values.env.KRAKEND_PORT | quote }}
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
      toPorts:
        - ports:
            - port: {{ .Values.env.IN_CAR_API_PORT | quote }}
              protocol: TCP
