apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.env.stage }}-postgres-secrets
  namespace: {{ .Values.env.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretstore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.env.stage }}-postgres-secrets
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.env.product }}-{{ .Values.env.stage }}-admin-username
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-admin-username
    - secretKey: {{ .Values.env.product }}-{{ .Values.env.stage }}-admin-password
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.env.stage }}-servicebus-secrets
  namespace: {{ .Values.env.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretstore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.env.stage }}-servicebus-secrets
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.env.product }}-{{ .Values.env.stage }}-service-bus-ns-connection-string
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-service-bus-ns-connection-string
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.env.stage }}-blob-secrets
  namespace: {{ .Values.env.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretstore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.env.stage }}-blob-secrets
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.env.stage }}-{{ .Values.blobStorage.dmb }}-primary-connection-string
      remoteRef:
        key: {{ .Values.env.stage }}-{{ .Values.blobStorage.dmb }}-primary-connection-string
    - secretKey: {{ .Values.env.stage }}-{{ .Values.blobStorage.incar }}-primary-connection-string
      remoteRef:
        key: {{ .Values.env.stage }}-{{ .Values.blobStorage.incar }}-primary-connection-string
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.env.stage }}-idk-client-secrets
  namespace: {{ .Values.env.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretstore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.env.stage }}-idk-secrets
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.env.product }}-{{ .Values.env.stage }}-idk-client-id
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-idk-client-id
    - secretKey: {{ .Values.env.product }}-{{ .Values.env.stage }}-idk-client-secret
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-idk-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.env.stage }}-cloud-idp-client-secrets
  namespace: {{ .Values.env.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretstore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.env.stage }}-cloud-idp-secrets
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.env.product }}-{{ .Values.env.stage }}-cloud-idp-client-id
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-cloud-idp-client-id
    - secretKey: {{ .Values.env.product }}-{{ .Values.env.stage }}-cloud-idp-client-secret
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-cloud-idp-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.env.stage }}-api-gateway-secrets
  namespace: {{ .Values.env.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretstore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.env.stage }}-api-gateway-secrets
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.env.product }}-{{ .Values.env.stage }}-blob-reader-client-id
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-blob-reader-client-id
    - secretKey: {{ .Values.env.product }}-{{ .Values.env.stage }}-blob-reader-client-secret
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-blob-reader-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.env.stage }}-dmcu-secrets
  namespace: {{ .Values.env.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretstore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.env.stage }}-dmcu-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        dmcu-cert.pfx: '{{ "{{ .dmcuCert | b64dec }}" }}'
        dmcu-pkcs12-password: '{{ "{{ .dmcuPassword }}" }}'
  data:
    - secretKey: dmcuPassword
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-dmcu-pkcs12-password
    - secretKey: dmcuCert
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-dmcu-pkcs12-cert
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.env.stage }}-oauth2-proxy-secrets
  namespace: {{ .Values.env.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretstore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.env.stage }}-oauth2-proxy-secrets
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-cloud-idp-client-id
    - secretKey: client-secret
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-cloud-idp-client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: {{ .Values.env.product }}-{{ .Values.env.stage }}-oauth2-proxy-cookie-secret
