apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretstore.name }}
  namespace: {{ .Values.env.namespace }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://{{ .Values.vault.name }}.vault.azure.net/
      serviceAccountRef:
        name: {{ .Values.serviceAccount.name }}
